apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blue-workloads
  namespace: flux-system
namePrefix: blue-
resources:
  - ../nginx
  - ../ingress.yaml
  - namespace.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx-deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      
      - op: replace
        path: /spec/template/metadata/labels/app
        value: blue-nginx
      
      - op: replace
        path: /spec/selector/matchLabels/app
        value: blue-nginx
    
  - target:
      version: v1
      kind: Service
      name: nginx-service
    patch: |     
      - op: replace
        path: /spec/selector/app
        value: blue-nginx