namePrefix: blue-
namespace: nginx
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nginx/
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ngixn-deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
