namePrefix: green-
resources:
  - ../nginx
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx-deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

      - op: replace
        path: /spec/template/metadata/labels/app
        value: green-nginx
      
      - op: replace
        path: /spec/selector/matchLabels/app
        value: green-nginx
        
  - target:
      version: v1
      kind: Service
      name: nginx-service
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30030
      
      - op: replace
        path: /spec/selector/app
        value: green-nginx
