namePrefix: green-
resources:
  - ../nginx
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ngixn-deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      version: v1
      kind: Service
      name: ngixn-service
    patch: |
      - op: replace
        path: /spec/ports/3/nodePort
        value: 30030
