namePrefix: green-
resources:
  - ../nginx
  - namespace.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ngixn-deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
