apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: akash42jb/database:122
        ports:
        - containerPort: 80
