apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: database
spec:
  selector:
    app: database
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 
    nodePort: 30007
  type: NodePort
